services:
  - type: web
    name: line-bot-webhook
    env: node
    buildCommand: npm install
    startCommand: ./start.sh
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    rootDir: .
